<?php

namespace SV\WarningImprovements\XF\Pub\Controller;

use XF\Mvc\ParameterBag;

/**
 * Extends \XF\Pub\Controller\Member
 */
class Member extends XFCP_Member
{
    public function actionView(ParameterBag $params)
    {
        return parent::actionView($params); // TODO: Change the autogenerated stub
    }

    public function actionWarningActions()
    {

    }

    public function actionWarn(ParameterBag $params)
    {
        return parent::actionWarn($params); // TODO: Change the autogenerated stub
    }

    public function actionWarnings(ParameterBag $params)
    {
        return parent::actionWarnings($params); // TODO: Change the autogenerated stub
    }

    public function actionTooltip(ParameterBag $params)
    {
        return parent::actionTooltip($params); // TODO: Change the autogenerated stub
    }
}