<?php

namespace SV\WarningImprovements\XF\Pub\Controller;

use XF\Mvc\ParameterBag;

/**
 * Extends \XF\Pub\Controller\Warning
 */
class Warning extends XFCP_Warning
{
    public function actionIndex(ParameterBag $params)
    {
        return parent::actionIndex($params); // TODO: Change the autogenerated stub
    }
}