<?php

namespace SV\WarningImprovements\XF\Admin\Controller;
use XF\Mvc\ParameterBag;

/**
 * Extends \XF\Admin\Controller\Warning
 */
class Warning extends XFCP_Warning
{
    public function actionIndex(ParameterBag $params)
    {
        return parent::actionIndex($params); // TODO: Change the autogenerated stub
    }

    public function actionLoadTree()
    {

    }

    public function actionSyncTree()
    {

    }

    public function actionRenameTreeItem()
    {

    }

    public function actionEdit(ParameterBag $params)
    {
        return parent::actionEdit($params); // TODO: Change the autogenerated stub
    }

    public function warningAddEdit(\XF\Entity\WarningDefinition $warning)
    {
        return parent::warningAddEdit($warning); // TODO: Change the autogenerated stub
    }

    public function actionSave(ParameterBag $params)
    {
        return parent::actionSave($params); // TODO: Change the autogenerated stub
    }

    public function _actionAddEdit(\XF\Entity\WarningAction $action)
    {
        return parent::_actionAddEdit($action); // TODO: Change the autogenerated stub
    }

    public function defaultActionAddEdit()
    {

    }

    public function actionDefaultEdit()
    {

    }

    public function actionDefaultSave()
    {

    }

    public function actionDefaultDelete()
    {

    }

    public function categoryAddEdit()
    {

    }

    public function actionCategoryAdd()
    {

    }

    public function actionCategoryEdit()
    {

    }

    public function actionCategorySave()
    {

    }

    public function actionCategoryDelete()
    {

    }
}