<?php

namespace SV\WarningImprovements\XF\Admin\Controller;

use XF\Mvc\FormAction;
use XF\Mvc\ParameterBag;

/**
 * Extends \XF\Admin\Controller\Warning
 */
class Warning extends XFCP_Warning
{
    public function actionIndex(ParameterBag $params)
    {
        return parent::actionIndex($params); // TODO: Change the autogenerated stub
    }

    public function actionLoadTree()
    {

    }

    public function actionSyncTree()
    {

    }

    public function actionRenameTreeItem()
    {

    }

    public function actionEdit(ParameterBag $params)
    {
        return parent::actionEdit($params); // TODO: Change the autogenerated stub
    }

    public function warningAddEdit(\XF\Entity\WarningDefinition $warning)
    {
        return parent::warningAddEdit($warning); // TODO: Change the autogenerated stub
    }

    public function actionSave(ParameterBag $params)
    {
        return parent::actionSave($params); // TODO: Change the autogenerated stub
    }

    public function _actionAddEdit(\XF\Entity\WarningAction $action)
    {
        return parent::_actionAddEdit($action); // TODO: Change the autogenerated stub
    }

    public function defaultActionAddEdit(\SV\WarningImprovements\Entity\WarningDefault $defaultAction)
    {
        $viewParams = [
            'actionAction' => $defaultAction
        ];
        return $this->view('XF:Warning\Action\Edit', 'warning_action_edit', $viewParams);
    }

    public function actionDefaultEdit(ParameterBag $params)
    {
        $defaultAction = $this->assertDefaultExists($params->warning_default_id);
        return $this->defaultActionAddEdit($defaultAction);
    }

    public function actionDefaultAdd()
    {
        /** @var \SV\WarningImprovements\Entity\WarningDefault $defaultAction */
        $defaultAction = $this->em()->create('SV\WarningImprovements:WarningDefault');
        return $this->defaultActionAddEdit($defaultAction);
    }

    protected function defaultSaveProcess(\SV\WarningImprovements\Entity\WarningDefault $defaultAction)
    {
        $form = $this->formAction();

        $input = $this->filter([
            'threshold_points' => 'uint',
            'expiry_extension' => 'uint',
            'expiry_type' => 'str',
            'active' => 'bool'
        ]);
        $form->basicEntitySave($defaultAction, $input);

        return $form;
    }

    public function actionDefaultSave(ParameterBag $params)
    {
        $this->assertPostOnly();

        if ($params->warning_default_id)
        {
            $defaultAction = $this->assertDefaultExists($params->warning_default_id);
        }
        else
        {
            /** @var \SV\WarningImprovements\Entity\WarningDefault $defaultAction */
            $defaultAction = $this->em()->create('SV\WarningImprovements:WarningDefault');
        }

        $this->defaultSaveProcess($defaultAction)->run();

        return $this->redirect(
            $this->buildLink('warnings') . $this->buildLinkHash('warning_default-' . $defaultAction->getEntityId())
        );
    }

    public function actionDefaultDelete(ParameterBag $params)
    {
        $defaultAction = $this->assertDefaultExists($params->warning_default_id);

        if ($this->isPost())
        {
            $defaultAction->delete();

            return $this->redirect($this->buildLink('warnings'));
        }
        else
        {
            $viewParams = [
                'defaultAction' => $defaultAction
            ];
            return $this->view('XF:Warning\DefaultDelete', 'sv_warningimprovements_warning_default_delete', $viewParams);
        }
    }

    public function categoryAddEdit(\SV\WarningImprovements\Entity\WarningCategory $category)
    {
        $viewParams = [
            'category' => $category,
            'categories' => $this->getCategoryRepo()->getWarningCategoryRoots(),
            'userGroups' => $this->repository('XF:UserGroup')->getUserGroupTitlePairs()
        ];
        return $this->view('XF:Warning\Category\Edit', 'sv_warning_category_edit', $viewParams);
    }

    public function actionCategoryAdd()
    {
        /** @var \SV\WarningImprovements\Entity\WarningCategory $category */
        $category = $this->em()->create('SV\WarningImprovements:WarningCategory');
        return $this->categoryAddEdit($category);
    }

    public function actionCategoryEdit(ParameterBag $params)
    {
        $category = $this->assertCategoryExists($params->warning_category_id);
        return $this->categoryAddEdit($category);
    }

    protected function categorySaveProcess(\SV\WarningImprovements\Entity\WarningCategory $category)
    {
        $form = $this->formAction();

        $input = $this->filter([
            'warning_category_id' => 'str',
            'parent_warning_category_id' => 'uint',
            'display_order' => 'uint',
            'allowed_user_group_ids' => 'array-uint'
        ]);

        $form->basicEntitySave($category, $input);

        $phraseInput = $this->filter([
            'title' => 'str'
        ]);
        $form->validate(function(FormAction $form) use ($phraseInput)
        {
            if ($phraseInput['title'] === '')
            {
                $form->logError(\Xf::phrase('please_enter_valid_title'), 'title');
            }
        });
        $form->apply(function() use ($phraseInput, $category)
        {
            foreach ($phraseInput AS $type => $text)
            {
                $masterPhrase = $category->getMasterPhrase($type);
                $masterPhrase->phrase_text = $text;
                $masterPhrase->save();
            }
        });

        return $form;
    }

    public function actionCategorySave(ParameterBag $params)
    {
        $this->assertPostOnly();

        if ($params->warning_category_id)
        {
            $category = $this->assertDefaultExists($params->warning_category_id);
        }
        else
        {
            /** @var \SV\WarningImprovements\Entity\WarningCategory $category */
            $category = $this->em()->create('SV\WarningImprovements:WarningCategory');
        }

        $this->categorySaveProcess($category)->run();

        return $this->redirect(
            $this->buildLink('warnings') . $this->buildLinkHash('warning_default-' . $category->getEntityId())
        );
    }

    public function actionCategoryDelete(ParameterBag $params)
    {
        $category = $this->assertDefaultExists($params->warning_category_id);

        if ($this->isPost())
        {
            $category->delete();

            return $this->redirect($this->buildLink('warnings'));
        }
        else
        {
            $viewParams = [
                'category' => $category
            ];
            return $this->view('XF:Warning\DefaultDelete', 'sv_warningimprovements_warning_default_delete', $viewParams);
        }
    }

    /**
     * @return \SV\WarningImprovements\Repository\WarningCategory
     */
    protected function getCategoryRepo()
    {
        return $this->repository('SV\WarningImprovements:WarningCategory');
    }

    /**
     * @param $id
     * @param null $with
     * @param null $phraseKey
     *
     * @return \SV\WarningImprovements\Entity\WarningCategory
     */
    protected function assertCategoryExists($id, $with = null, $phraseKey = null)
    {
        return $this->assertRecordExists('SV\WarningImprovements:WarningCategory', $id, $with, $phraseKey);
    }

    /**
     * @param $id
     * @param null $with
     * @param null $phraseKey
     *
     * @return \SV\WarningImprovements\Entity\WarningDefault
     */
    protected function assertDefaultExists($id, $with = null, $phraseKey = null)
    {
        return $this->assertRecordExists('SV\WarningImprovements:WarningDefault', $id, $with, $phraseKey);
    }
}